#!/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2010, 2011, Oracle and/or its affiliates. All rights reserved.
#

# Create the table of includes for euro.h
# from the list of conversion tables in $tbls/.
# Sanitize '-'.

tbls="tbls"

print_include() {
	# include default non-identical fallback char
	fallback=`echo $1 | perl -pe "s:\.tbl:\.fb:"`; 

	[[ -f "$fallback" ]] && {
		printf "#define ICV_NON_IDENTICAL_REPLACEMENT_CHAR	`cat $fallback`\n";
	}
	printf "static const table_component_t tbl[256] = {\n"
	printf "#include \"$1\"\n"
	printf "};\n"
}

print_includes() {

	[[ -z "$1" ]] && { echo "ERROR: missing files: $tbls/*tbl"; exit 1; }

	perlre='s:'$tbls'/:T_: ; s:\.tbl:: ; s:-::g'

	# first entry
	T_=`echo $1 | perl -pe "$perlre"`; 
	printf "#if defined($T_)\n"
	print_include "$1"
	shift
	
	# elifs
	while [[ -n "$1" ]]; do
		T_=`echo $1 | perl -pe "$perlre"`; 
		printf "\n#elif defined ($T_)\n"
		print_include "$1"
		shift
	done

	# else
	printf "\n#else\n"
	printf "#error	\"Error - nothing defined.\"\n"
	printf "#endif\n"
}

print_includes $(ls $tbls/*tbl)

